{% set name = "trino-server" %}
{% set version = "434" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  # Build needs a proper Git checkout.
  git_url: https://github.com/trinodb/trino
  git_rev: "{{ version }}"

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    # From libprocname, which is shipped as part of Trino
    - /lib64/libc.so.6  # [linux]

requirements:
  build:
    - openjdk =17
    - maven
    - patchelf
  run:
    - openjdk =17
    - __unix

test:
  commands:
    - trino-server --help

about:
  home: https://trino.io
  summary: Trino is a fast distributed SQL query engine for big data analytics.
  description: |
    Trino is a distributed SQL query engine designed to query large data sets distributed over one or more heterogeneous data sources.
  license: Apache-2.0
  license_file:
    - LICENSE
    - core/trino-server/target/trino-server-{{ version }}/NOTICE
    - target/generated-sources/license/THIRD-PARTY.txt
  doc_url: https://trino.io/docs/current/
  dev_url: https://github.com/trinodb/trino

extra:
  recipe-maintainers:
    - jonashaag
